### ISSUE TITLE
Error en prepare()

### ISSUE THREAD

**Issue by juank2808** [juank2808/To-Do-app-V2#2]
@zmwebdev error en el prepare
`    require_once('conexion/connect.php');

  try {
        $sth =  $mbd->**prepare**("SELECT \* from listas;");
        $sth->execute();
        $result = $sth->fetchAll();

```
    print_r($result);

    $mbd = null;
} catch (PDOException $e) {
    print "Error!: " . $e->getMessage() . "<br/>";
    die();

}`
```

**Comment by zmwebdev** [comment]
¿Puedes poner el mensaje de error que da?

**Comment by juank2808** [comment]
![captura](https://cloud.githubusercontent.com/assets/14195668/18725530/e5f69210-8040-11e6-8c76-5a4eb1393eac.PNG)

**Comment by zmwebdev** [comment]
tienes el error pq pones a null $mdb

``` php
    $mbd = null;
```
