### ISSUE TITLE
¿por que no me me sale nada ?

### ISSUE THREAD

**Issue by juank2808** [juank2808/To-Do-app-V2#3]
@zmwebdev hay un problema con el resultado de la consulta para que me aparezca el resultado de la consulta en forma de lista

![image](https://cloud.githubusercontent.com/assets/14195668/18784592/77ce1c14-8193-11e6-8e0d-48204f65ee55.png)

el documento esta ubicado en **todo-app-v2/paginas/Listas.php**

**Comment by zmwebdev** [comment]
veo que tienes puesto 

``` php
$mbd = null;
```

en https://github.com/juank2808/To-Do-app-V2/blob/master/paginas/getList.php#L14

**Comment by juank2808** [comment]
sigue sin funcionar  @zmwebdev ¿que mas deberia hacer?

**Comment by zmwebdev** [comment]
No te muestra ningun dato ya que no tienes datos de las listas y tareas en la base de datos. Crea unas Insert (listas, tareas) y prueba de nuevo. con este código:

``` php
    // send HTML
    // $result: all lists
    foreach ($result as $row) {
        print $row["ID"] . "-" . $row["nombre"] ."<br/>";
    }
```

El ejemplo lo tienes en este fichero:
https://github.com/zmwebdev/php-todo-app/blob/v1/getListsHTML.php
